// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7_OnNpSJJnIHg-4zfb_3A-kqjP_GfbD8',
    appId: '1:80433430503:web:9324ba9b7946114a674742',
    messagingSenderId: '80433430503',
    projectId: 'chat-app-cddba',
    authDomain: 'chat-app-cddba.firebaseapp.com',
    storageBucket: 'chat-app-cddba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4i0QnAihFBQ77U9cKlIjjidoHiTtmTmw',
    appId: '1:80433430503:android:ed7c4857ca8223c5674742',
    messagingSenderId: '80433430503',
    projectId: 'chat-app-cddba',
    storageBucket: 'chat-app-cddba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXr7QtOh-L5vf11XWeUpbGD8-mXAg_cj4',
    appId: '1:80433430503:ios:053d08eea216e3be674742',
    messagingSenderId: '80433430503',
    projectId: 'chat-app-cddba',
    storageBucket: 'chat-app-cddba.appspot.com',
    iosClientId: '80433430503-c5hq2ikdbmq2kh37hd5id5bajpnj779a.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXr7QtOh-L5vf11XWeUpbGD8-mXAg_cj4',
    appId: '1:80433430503:ios:053d08eea216e3be674742',
    messagingSenderId: '80433430503',
    projectId: 'chat-app-cddba',
    storageBucket: 'chat-app-cddba.appspot.com',
    iosClientId: '80433430503-c5hq2ikdbmq2kh37hd5id5bajpnj779a.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
